# Generated by Django 5.1.2 on 2024-10-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_floor_alter_flat_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='realty.building', verbose_name='Корпус')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flats', to='realty.section', verbose_name='Секция'),
        ),
    ]
