# Generated by Django 5.1.2 on 2024-10-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_section_flat_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(default='Без адреса', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='building',
            name='flats_number',
            field=models.PositiveSmallIntegerField(default=54, verbose_name='Кол-во квартир'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_number',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='Кол-во этажей'),
        ),
    ]
