# Generated by Django 5.1.2 on 2024-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_building_address_building_flats_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='building',
            name='flats_number',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во квартир'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floor_number',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во этажей'),
        ),
    ]
