# Generated by Django 5.1.2 on 2024-10-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_alter_building_address_alter_building_flats_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='flats_number',
        ),
        migrations.RemoveField(
            model_name='building',
            name='floor_number',
        ),
    ]
