# Generated by Django 5.1.2 on 2024-10-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_remove_flat_settlement_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='building',
            name='settlement_before',
            field=models.DateField(verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='metro',
            field=models.CharField(max_length=100, verbose_name='Метро'),
        ),
    ]
