# Generated by Django 5.1.2 on 2024-10-22 21:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plans/', verbose_name='Картинка планировки')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Кол-во комнат')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь')),
                ('kitchen_area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кухня')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
            },
        ),
        migrations.RemoveField(
            model_name='flat',
            name='area',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='kitchen_area',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='rooms',
        ),
        migrations.AddField(
            model_name='flat',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='realty.plan', verbose_name='Планировка'),
        ),
    ]
