# Generated by Django 5.1.2 on 2024-10-22 22:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_plan_remove_flat_area_remove_flat_kitchen_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(default='buildings/default.jpg', upload_to='buildings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Картинка корпуса'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='realty.plan', verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(upload_to='plans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Картинка планировки'),
        ),
    ]
